name: Instagram Auto Post

on:
  schedule:
    - cron: "40 1 * * *"    # 7:10 AM IST
    - cron: "40 6 * * *"    # 12:10 PM IST
    - cron: "40 12 * * *"   # 6:10 PM IST
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run post script
        run: node scripts/post.js
        env:
          GOOGLE_SERVICE_KEY: ${{ secrets.GOOGLE_SERVICE_KEY }}
          SOURCE_FOLDER_ID: ${{ secrets.SOURCE_FOLDER_ID }}
          POSTED_FOLDER_ID: ${{ secrets.POSTED_FOLDER_ID }}
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_REPO: ${{ secrets.GH_REPO }}
